INSERT INTO USER (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE) VALUES ('A', 'A', 'A', 'A','A', 'ROLE_USER')

INSERT INTO EVENT (NAME, USER_ID, EVENT_DATE, LOCATION) VALUES ('ABC', '1', '2017-08-10 12:12:12', 'São Paulo')